### ISSUE TITLE
Container image does not correctly handle SIGTERM signal

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks-postman-runtime#23]
### Describe the bug

When running the arm64 container image on Mac M1, it appears that terminating the process does not quit and kill the container image. I'm running the `nightly` image that matches `0.4.0-SNAPSHOT`.

### Expected behavior

When running the `0.2.0` image (only x86 version, not an arm64 one), hitting Ctrl+C terminates the container process as expected.

### Actual behavior

Just running the following command, hit Ctrl+C:

```sh
$ docker run -p 3000:3000 -it quay.io/microcks/microcks-postman-runtime:nightly 
Microcks postman-runtime wrapper listening on port: 3000
^C
```

and you'll see the process still there:

```sh
$ docker ps
CONTAINER ID   IMAGE                                               COMMAND                  CREATED         STATUS         PORTS                              NAMES
9c9496e42fe4   quay.io/microcks/microcks-postman-runtime:nightly   "docker-entrypoint.s…"   5 minutes ago   Up 5 minutes   0.0.0.0:3000->3000/tcp             nice_fermi
```
You'll need to `docker kill 9c9496e42fe4` to actually get it terminated.

### Microcks version or git rev

`latest`, `0.3.0` and `nightly`

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker

### Additional information

Only tested on Mac M1

**Comment by yada** [comment]
Issue confirmed on Apple M2 Pro but also on **Linux** Ubuntu 23.10:

**x86_64**:
```
yacine@yadadesk:~$ uname -a
Linux yadadesk 6.5.0-44-generic #44-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 15:10:09 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

Tested using **Docker 24.0.7**:
```
yacine@yadadesk:~$ sudo docker version
Client:
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.21.1
 Git commit:        24.0.7-0ubuntu2~23.10.1
 Built:             Wed Mar 13 20:05:50 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.21.1
  Git commit:       24.0.7-0ubuntu2~23.10.1
  Built:            Wed Mar 13 20:05:50 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.12
  GitCommit:
 runc:
  Version:          1.1.12-0ubuntu2~23.10.1
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
```

CTRL-C does not kill the docker image, so this **issue is global and not related to ARM vs x86**:
```
yacine@yadadesk:~$ sudo docker run -p 3000:3000 -it quay.io/microcks/microcks-postman-runtime:nightly
Unable to find image 'quay.io/microcks/microcks-postman-runtime:nightly' locally
nightly: Pulling from microcks/microcks-postman-runtime
7264a8db6415: Pull complete
eee371b9ce3f: Pull complete
93b3025fe103: Pull complete
d9059661ce70: Pull complete
a4b22a8946c4: Pull complete
4f4fb700ef54: Pull complete
0c195b58275a: Pull complete
7f78e34cbcdf: Pull complete
815e409affec: Pull complete
Digest: sha256:fcddfc825037b273611cadeeceaf23670d3e64ffc4c6c66163d20c82f2745b01
Status: Downloaded newer image for quay.io/microcks/microcks-postman-runtime:nightly
Microcks postman-runtime wrapper listening on port: 3000
^C
```

The container is **still running**:
```
yacine@yadadesk:~$ sudo docker ps
CONTAINER ID   IMAGE                                               COMMAND                  CREATED         STATUS         PORTS                                       NAMES
ec04723baff3   quay.io/microcks/microcks-postman-runtime:nightly   "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   relaxed_carson
```

**Comment by yada** [comment]
Fix using:
```
yacine@yadadesk:~$ sudo docker run -p 3000:3000 -it **--init** quay.io/microcks/microcks-postman-runtime:nightly
Microcks postman-runtime wrapper listening on port: 3000
^Cyacine@yadadesk:~$
```

Ref: https://github.com/nodejs/docker-node/blob/7f99010af378daa2520bb60435d0e91e20950d82/docs/BestPractices.md#handling-kernel-signals

**Comment by yada** [comment]
BTW, maybe the opportunity to use a more recent version of the node alpine image?
From 16 to 22:
https://hub.docker.com/_/node

To remove CVE:
https://snyk.io/test/docker/node%3A16-alpine
https://snyk.io/test/docker/node%3A22-alpine

**Comment by lbroudoux** [comment]
I've upgraded to Red Hat UBI9 image to get alignment on other images used in Microcks components.
The new image is now using node 20 as a basis. I've also created issue #30 to work on updating dependencies.
